# Setup
title:               Alex Yang
tagline:             "Alex's Personal Website"
description:         'I am a developer @ Microsoft currently working the Docker extension for VSCode. I am passionate about developer tools and improving the developer experience.'
baseurl:             ''
url:                 'https://www.yangalex.com/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alex Yang
  email:             alexyangncsu@gmail.com
  github_username:   alexyaang

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
